project_id = "kdhhbkzjibwuelytgroj"

[functions.get-booking-config]
verify_jwt = false

[functions.get-availability]
verify_jwt = false

[functions.get-service-catalog]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.admin-set-staff]
verify_jwt = true

[functions.customer-auth]
verify_jwt = false

[functions.customer-bookings]
verify_jwt = false

[functions.staff-auth]
verify_jwt = false
