/*
  # Sync bookings table structure with application logic

  1. Changes
    - Ensure all required columns exist with correct types
    - Set proper NULL/NOT NULL constraints
    - Add missing columns if they don't exist
    - Ensure booking_number can be NULL (generated by trigger)
    - Ensure city is nullable (optional field)
    - Ensure comments is nullable (optional field)
    - Ensure updated_at is nullable (set by trigger)
    - Ensure deleted_at is nullable (soft delete)
    - Ensure technician_notes is nullable (optional field)

  2. Structure
    - id: uuid, PRIMARY KEY, NOT NULL
    - booking_number: text, UNIQUE, NULL (generated by trigger)
    - first_name: text, NOT NULL
    - last_name: text, NOT NULL
    - phone: text, NOT NULL
    - address: text, NOT NULL
    - city: text, NULL (optional)
    - operating_system: text, NOT NULL
    - comments: text, NULL (optional)
    - appointment_date: timestamptz, NOT NULL
    - created_at: timestamptz, NOT NULL, DEFAULT now()
    - updated_at: timestamptz, NULL (set by trigger)
    - completed: boolean, NOT NULL, DEFAULT false
    - technician_notes: text, NULL (optional)
    - deleted_at: timestamptz, NULL (soft delete)
*/

-- Ensure all columns exist with correct types and constraints

-- booking_number (should be nullable, generated by trigger)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                 WHERE table_name = 'bookings' AND column_name = 'booking_number') THEN
    ALTER TABLE bookings ADD COLUMN booking_number TEXT UNIQUE;
  ELSE
    -- Make sure it can be NULL (for trigger generation)
    ALTER TABLE bookings ALTER COLUMN booking_number DROP NOT NULL;
  END IF;
END $$;

-- city (should be nullable, optional field)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                 WHERE table_name = 'bookings' AND column_name = 'city') THEN
    ALTER TABLE bookings ADD COLUMN city TEXT;
  ELSE
    -- Ensure it's nullable
    ALTER TABLE bookings ALTER COLUMN city DROP NOT NULL;
  END IF;
END $$;

-- updated_at (should be nullable, set by trigger)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                 WHERE table_name = 'bookings' AND column_name = 'updated_at') THEN
    ALTER TABLE bookings ADD COLUMN updated_at TIMESTAMPTZ;
  ELSE
    -- Ensure it's nullable
    ALTER TABLE bookings ALTER COLUMN updated_at DROP NOT NULL;
  END IF;
END $$;

-- deleted_at (should be nullable, soft delete)
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                 WHERE table_name = 'bookings' AND column_name = 'deleted_at') THEN
    ALTER TABLE bookings ADD COLUMN deleted_at TIMESTAMPTZ;
  ELSE
    -- Ensure it's nullable
    ALTER TABLE bookings ALTER COLUMN deleted_at DROP NOT NULL;
  END IF;
END $$;

-- Ensure required fields are NOT NULL (with safe handling)
DO $$ 
BEGIN
  -- Set NOT NULL constraints only if column exists and doesn't have NOT NULL already
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'first_name') THEN
    ALTER TABLE bookings ALTER COLUMN first_name SET NOT NULL;
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'last_name') THEN
    ALTER TABLE bookings ALTER COLUMN last_name SET NOT NULL;
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'phone') THEN
    ALTER TABLE bookings ALTER COLUMN phone SET NOT NULL;
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'address') THEN
    ALTER TABLE bookings ALTER COLUMN address SET NOT NULL;
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'operating_system') THEN
    ALTER TABLE bookings ALTER COLUMN operating_system SET NOT NULL;
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'appointment_date') THEN
    ALTER TABLE bookings ALTER COLUMN appointment_date SET NOT NULL;
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'created_at') THEN
    ALTER TABLE bookings ALTER COLUMN created_at SET NOT NULL;
    ALTER TABLE bookings ALTER COLUMN created_at SET DEFAULT now();
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'completed') THEN
    ALTER TABLE bookings ALTER COLUMN completed SET NOT NULL;
    ALTER TABLE bookings ALTER COLUMN completed SET DEFAULT false;
  END IF;
END $$;

-- Ensure optional fields are nullable
DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'comments') THEN
    ALTER TABLE bookings ALTER COLUMN comments DROP NOT NULL;
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'technician_notes') THEN
    ALTER TABLE bookings ALTER COLUMN technician_notes DROP NOT NULL;
  END IF;
END $$;

-- Ensure booking_number has unique constraint if it doesn't exist
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'bookings_booking_number_key'
  ) THEN
    ALTER TABLE bookings ADD CONSTRAINT bookings_booking_number_key UNIQUE (booking_number);
  END IF;
END $$;

